# Mathematics for Machine Learning Pre-Class assignment 3 Matrix Scratch

In [7]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

<hr>

**[Problem 1] Matrix product is calculated manually**

<hr>

$ A = \begin{bmatrix}-1 & 2 & 3\\4 & -5 & 6\\7 & 8 & -9\end{bmatrix}$
$ B = \begin{bmatrix}0 & 2 & 1\\0 & 2 & -8\\2 & 9 & -1\end{bmatrix}$

But to multiply a matrix by another matrix we need to do the "dot product" of rows and columns example: 

The "Dot Product" is where we multiply matching members, then sum up:

1st row and 1st column: $(-1, 2, 3) \cdot (0, 0, 2) = -1*0 + 2*0 + 3*2 = 6$

We match the 1st members (-1 and 0), multiply them, likewise for the 2nd members (2 and -) and the 3rd members (3 and 2), and finally sum them up and push it in to the 1st row 1st column of product matrix

$ Product\_matrix = \begin{bmatrix}6 &  &  \\ &  & \\ &  & \end{bmatrix}$

1st row and 2nd column: $(-1, 2, 3) \cdot (2, 2, 9) = -1*2 + 2*2 + 3*9 = 29$

$ Product\_matrix = \begin{bmatrix}6 & 29 &  \\ &  & \\ &  & \end{bmatrix}$

1st row and 3rd column: $(-1, 2, 3) \cdot (1, -8, -1) = -1*1 + 2*-8 + 3*-1 = -20$

$ Product\_matrix = \begin{bmatrix}6 & 29 & -20 \\ &  & \\ &  & \end{bmatrix}$

2nd row and 1st column: $(4, -5, 6) \cdot (0, 0, 2) = 4*0 + -5*0 + 6*2 = 12$

$ Product\_matrix = \begin{bmatrix}6 & 29 & -20 \\12 &  & \\ &  & \end{bmatrix}$

2nd row and 2nd column: $(4, -5, 6) \cdot (2, 2, 9) = 4*2 + -5*2 + 6*9 = 52$

$ Product\_matrix = \begin{bmatrix}6 & 29 & -20 \\12 & 52 & \\ &  & \end{bmatrix}$

2nd row and 3rd column: $(4, -5, 6) \cdot (1, -8, -1) = 4*1 + -5*-8 + 6*-1 = 38$

$ Product\_matrix = \begin{bmatrix}6 & 29 & -20 \\12 & 52 & 38 \\ &  & \end{bmatrix}$

3rd row and 1st column: $(7, 8, -9) \cdot (0, 0, 2) = 7*0 + 8*0 + -9*2 = -18$

$ Product\_matrix = \begin{bmatrix}6 & 29 & -20 \\12 & 52 & 38 \\-18 &  & \end{bmatrix}$

3rd row and 2nd column: $(7, 8, -9) \cdot (2, 2, 9) = 7*2 + 8*2 + -9*9 = -51$

$ Product\_matrix = \begin{bmatrix}6 & 29 & -20 \\12 & 52 & 38 \\-18 & -51  & \end{bmatrix}$

3rd row and 3rd column: $(7, 8, -9) \cdot (1, -8, -1) = 7*1 + 8*-8 + -9*-1 = -48$

$ Product\_matrix = \begin{bmatrix}6 & 29 & -20 \\12 & 52 & 38 \\-18 & -51  & -48 \end{bmatrix}$

so:

$ \begin{bmatrix} -1 & 2 & 3 \\ 4 & -5 & 6 \\ 7 & 8 & -9 \end{bmatrix}  +  \begin{bmatrix} 0 & 2 & 1 \\ 0 & 2 & -8 \\ 2 & 9 & -1 \end{bmatrix} = \begin{bmatrix} 6 & 29 & -20 \\ 12 & 52 & 38 \\ -18 & -51  & -48 \end{bmatrix}$


<hr>

**[Problem 2] Calculation by NumPy function**

<hr>

In [8]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

p_ndarray = np.matmul(a_ndarray,b_ndarray)

print("Product matrix in matmul method \n{}".format(p_ndarray))


Product matrix in matmul method 
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


<hr>

**[Problem 3] Implementation of calculation of a certain element**

<hr>

In [9]:
def mul_certain_element(A, B): 
    m = 0
    for k in range(len(A)):
        m += A[0,k]*B[k,0]
    return m

m = mul_certain_element(a_ndarray, b_ndarray)

print("certain element in (0,0) of a_ndarray * b_ndarray : {}".format(m))

certain element in (0,0) of a_ndarray * b_ndarray : 6


<hr>

**[Problem 4] Creating a function that performs matrix multiplication**

<hr>

In [10]:
def mul(A,B):
    m = np.array([0] *(A.shape[0]*B.shape[1])).reshape(A.shape[0],B.shape[1])
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                m[i][j] += A[i][k] * B[k][j]
    return m

m = mul(a_ndarray, b_ndarray)

print("Product matrix in function \n{}".format(m))

Product matrix in function 
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


<hr>

**[Problem 5] Judge the input whose calculation is not defined**

<hr>

In [11]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

def mul(A,B):
    if (A.shape[1] == B.shape[0]):
        print("the number of columns of A ({}) is equal to the number of rows of B ({}) \n".format(A.shape[1], B.shape[0]))
        m = np.array([0] *(A.shape[0]*B.shape[1])).reshape(A.shape[0],B.shape[1])
        for i in range(A.shape[0]):
            for j in range(B.shape[1]):
                for k in range(A.shape[1]):
                    m[i][j] += A[i][k] * B[k][j]
        print("And then the product matrix is : \n{}".format(m))
    else :
        print("the number of columns of A ({}) is not equal to the number of rows of B ({})".format(A.shape[1], B.shape[0]))
    

mul(d_ndarray, e_ndarray)


the number of columns of A (3) is not equal to the number of rows of B (2)


<hr>

**[Problem 6] Transposition**

<hr>

In [12]:
def mul(A,B):
    if (A.shape[1] == B.shape[0]):
        m = np.array([0] *(A.shape[0]*B.shape[1])).reshape(A.shape[0],B.shape[1])
        for i in range(A.shape[0]):
            for j in range(B.shape[1]):
                for k in range(A.shape[1]):
                    m[i][j] += A[i][k] * B[k][j]
        return m
    else :
        print("the number of columns of A ({}) is not equal to the number of rows of B ({})\n".format(A.shape[1], B.shape[0]))
        print("So we need to transposition for \n {} \nto \n{}".format(B, B.T))
        B = B.T
        m = np.array([0] *(A.shape[0]*B.shape[1])).reshape(A.shape[0],B.shape[1])
        for i in range(A.shape[0]):
            for j in range(B.shape[1]):
                for k in range(A.shape[1]):
                    m[i][j] += A[i][k] * B[k][j]
        return m

m = mul(d_ndarray, e_ndarray)

print("\nthe product matrix with Transposition: \n{} ".format(m))

the number of columns of A (3) is not equal to the number of rows of B (2)

So we need to transposition for 
 [[-9  8  7]
 [ 6 -5  4]] 
to 
[[-9  6]
 [ 8 -5]
 [ 7  4]]

the product matrix with Transposition: 
[[ 46  -4]
 [-34  73]] 
