# Utilization of Object Orientation

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
import pandas as pd 
%matplotlib inline

In [8]:
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("Mean :", scaler.mean_)
print("Var  :", scaler.var_)
X_std = scaler.transform(X)
print(X_std)

Mean : [4.86 3.31 1.45 0.22]
Var  : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


<hr>

**[Problem 1] Enumeration of classes used so far**

<hr>

* pandas

DataFrame: A class with a two-dimensional data structure

* matplotlib

patches class: Matplotlib's simple drawing module

colors class: Module to control colors with Matplotlib

* scikit-learn

datasets: A dataset module that stores data such as iris variety data and housing price data for Boston City.

<hr>

**[Problem 2] Enumeration of methods and instance variables used so far**

<hr>

Method
* Numerical calculation system

sum (), max (), min (), abs (), round ()

* Type related

dict (), int (), float (), set (), list (), str ()

* List, iterator processing system

all (), any (), enumerate (), len ()
* Character string system

ascii ()

Instance variables
reshape, shape, dtype, column, index, mean, var

<hr>

**[Problem 3] Creating a standardized class by scratch**

<hr>

In [6]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)
        pass
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_) / np.sqrt(self.var_)
        pass
        return X_scaled

In [7]:
import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


<hr>

**[Problem 4] Creating a class that performs 4 arithmetic operations**

<hr>

In [25]:
import warnings

class ExampleClass():

    def __init__(self, value):
        if not isinstance(value, (int, float, complex)):
            warnings.warn("Value is a numeric value")
            self.value = 0
        else :
            self.value = value
    def add(self, value2):
        self.value += value2
    def sub(self, value2):
        self.value -= value2
    def mul(self, value2):
        self.value *= value2
    def div(self, value2):
        if value == 0:
            warnings.warn("Div to 0")
        else :
            self.value /= value2

In [21]:
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))

value : 5
value : 8


In [29]:
example = ExampleClass(5)
print("value : {}".format(example.value))
example.sub(3)
print("value : {}".format(example.value))

value : 5
value : 2


In [28]:
example = ExampleClass(5)
print("value : {}".format(example.value))
example.mul(3)
print("value : {}".format(example.value))

value : 5
value : 15


In [27]:
example = ExampleClass(5)
print("value : {}".format(example.value))
example.div(3)
print("value : {}".format(example.value))

value : 5
value : 1.6666666666666667


In [26]:
example = ExampleClass("1234")
print("value : {}".format(example.value))
example.div(3)
print("value : {}".format(example.value))

value : 0
value : 0.0
<ipython-input-25-4d220b668211>:7: UserWarning: Value is a numeric value
  warnings.warn("Value is a numeric value")
